name: Java CI with Maven

on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: ~/.m2/repository
        key: maven-repo

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: sonar

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Test with Maven
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=samply_icd-dictionary
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USENAME: ${{ github.actor }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2.1.2
      with:
        path: |
          ~/.m2/repository
        key: maven-repo

    - name: Build with Maven
      run: mvn -B package -DskipTests -Dmaven.javadoc.skip=true

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ghcr.io/samply/icd10-dictionary:${{ github.sha }}
        push: true
