name: Java CI with Maven

on:
  push:
    branches:
    - main
    - develop
    tags:
    - v[0-9]+.[0-9]+.[0-9]+**
  pull_request:
    branches:
    - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-repo-test-${{ hashFiles('pom.xml') }}

    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: sonar

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1

    - name: Test with Maven
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=samply_icd-dictionary
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USENAME: ${{ github.actor }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Local Maven Repo
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-repo-build-${{ hashFiles('pom.xml') }}

    - name: Build with Maven
      run: mvn -B package -DskipTests -Dmaven.javadoc.skip=true

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker meta
      id: docker-meta
      uses: docker/metadata-action@v3
      with:
        images: |
          samply/icd-dictionary
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,format=long

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: samply/icd-dictionary:sha-${{ github.sha }}
        format: template
        template: '@/contrib/sarif.tpl'
        output: trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@codeql-bundle-20211208
      with:
        sarif_file: trivy-results.sarif
